const views=[['overview','Overview'],['chat','Chat'],['channels','Channels'],['models','Model'],['skills','Skills'],['tools','Tools'],['capabilities','Capabilities'],['activity','Activity'],['settings','Settings']]
let snapshot=null,active='overview',events=[],approval=null,currentSession=null,messages=[],seq=0
const pending=new Map(),main=document.querySelector('#main'),nav=document.querySelector('#nav')
function call(method,params={}){const id=++seq;webkit.messageHandlers.helios.postMessage({id,method,params});return new Promise((resolve,reject)=>pending.set(id,{resolve,reject}))}
window.__heliosReceive=message=>{if(message.event){events.unshift(message);events=events.slice(0,200);if(message.event==='approval'){approval=message;renderApproval()}if(message.event==='bridge.error'){main.innerHTML=notice('Unable to connect',message.message)}if(active==='activity')render()}else{const item=pending.get(message.id);if(!item)return;pending.delete(message.id);message.error?item.reject(new Error(message.error)):item.resolve(message.result)}}
views.forEach(([id,label])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{active=id;render()};b.dataset.id=id;nav.appendChild(b)})
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function notice(title,detail){return '<div class="notice"><h1>'+esc(title)+'</h1><p>'+esc(detail)+'</p></div>'}
function heading(title,detail,action=''){return '<div class="heading"><div><h1>'+esc(title)+'</h1><p>'+esc(detail)+'</p></div>'+action+'</div>'}
function row(title,detail,end=''){return '<div class="row"><div class="grow"><div class="title">'+esc(title)+'</div><div class="detail">'+esc(detail||'')+'</div></div>'+end+'</div>'}
function panel(title,content){return '<section class="panel"><div class="panel-title">'+esc(title)+'</div>'+content+'</section>'}
function list(title,detail,items,format){return heading(title,detail)+panel(items.length+' items',items.length?items.map(format).join(''):'<div class="blank">No '+esc(title.toLowerCase())+' found.</div>')}
function render(){if(!snapshot)return;document.querySelector('#health').textContent=snapshot.agent.status+' · v'+snapshot.agent.version;nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.id===active));const a=snapshot.agent
 if(active==='overview'){const metrics=[['Sessions',snapshot.sessions.length],['Channels',snapshot.channels.filter(x=>x.connected).length],['Skills',snapshot.skills.length],['Capabilities',snapshot.capabilities.length]].map(x=>'<div class="metric"><span class="label">'+x[0]+'</span><strong>'+x[1]+'</strong></div>').join('');main.innerHTML=heading('Local agent console',(a.provider||'No provider')+' / '+(a.model||'Not configured')+' · '+(a.workspace||'No workspace'),'<button class="button primary" id="newchat">new chat</button>')+'<div class="grid">'+metrics+'</div><div class="grid two">'+panel('Scheduled jobs',snapshot.jobs.length?snapshot.jobs.map(x=>row(x.name,x.expression)).join(''):'<div class="blank">No cron jobs configured.</div>')+panel('Recent activity',events.length?events.slice(0,5).map(x=>row(x.event,describe(x))).join(''):'<div class="blank">Activity appears when Helios works.</div>')+'</div>';document.querySelector('#newchat').onclick=()=>{active='chat';render()}}
 if(active==='channels')main.innerHTML=list('Channels','Credentials remain in macOS Keychain.',snapshot.channels,x=>row(x.name,x.allowedSenders.length+' allowed sender(s)','<span class="tag '+(x.connected?'online':'')+'">'+(x.connected?'connected':'off')+'</span>'))
 if(active==='models')main.innerHTML=list('Model','Desktop uses the provider configured by Helios.',snapshot.providers,x=>row(x.label,x.active?(a.model||x.defaultModel):x.defaultModel,x.active?'<span class="tag online">active</span>':''))
 if(active==='skills'){main.innerHTML=list('Skills','Installed instruction-only skills.',snapshot.skills,x=>row(x.name,x.source,'<button class="button danger remove-skill" data-id="'+esc(x.id)+'">remove</button>'));document.querySelectorAll('.remove-skill').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this skill from Helios?'))return;await call('skill.remove',{id:b.dataset.id});await reload()})}
 if(active==='tools'){main.innerHTML=list('Tools','Changes update the real Helios configuration.',snapshot.tools,x=>row(x.name,x.description,'<button class="toggle '+(x.enabled?'on':'')+'" data-id="'+esc(x.id)+'"></button>'));document.querySelectorAll('.toggle').forEach(b=>b.onclick=async()=>{const item=snapshot.tools.find(x=>x.id===b.dataset.id);await call('config.set',{key:item.id+'.enabled',value:!item.enabled});await reload()})}
 if(active==='capabilities'){main.innerHTML=list('Learned capabilities','Approved reusable playbooks.',snapshot.capabilities,x=>row(x.name,x.trigger,'<span class="tag">rev '+x.revision+' · '+(x.uses||0)+' uses</span> <button class="button danger forget" data-id="'+esc(x.id)+'">forget</button>'));document.querySelectorAll('.forget').forEach(b=>b.onclick=async()=>{if(!confirm('Permanently forget this learned capability?'))return;await call('capability.remove',{id:b.dataset.id});await reload()})}
 if(active==='activity')main.innerHTML=list('Live activity','Events from this Desktop session.',events,(x)=>row(x.event,describe(x)))
 if(active==='settings'){main.innerHTML=heading('Settings','Real local configuration and install status.')+panel('Autonomy',row(a.autonomy,'High-risk actions always require approval.','<button id="autonomy" class="toggle '+(a.autonomy==='autonomous'?'on':'')+'"></button>'))+panel('Local installation',row('Helios '+a.version,a.workspace||'Workspace not configured')+row('Background service',a.service)+row('Memory',a.memory||'local')+row('Distribution','Optional macOS app. The CLI installer never installs Desktop.'));document.querySelector('#autonomy').onclick=async()=>{snapshot=await call('config.set',{key:'autonomy.mode',value:a.autonomy==='guarded'?'autonomous':'guarded'});render()}}
 if(active==='chat')renderChat()
}
function renderChat(){if(!currentSession)currentSession=snapshot.sessions[0]?.id||crypto.randomUUID();main.innerHTML='<div class="chat">'+heading('Chat',(snapshot.agent.provider||'')+'/'+(snapshot.agent.model||''))+'<div class="messages">'+(messages.length?messages.filter(x=>x.role!=='tool').map(x=>'<div class="message '+esc(x.role)+'"><div class="bubble">'+esc(x.content)+'</div></div>').join(''):'<div class="blank">Start a real local Helios session.</div>')+'</div><div class="composer"><input id="prompt" placeholder="Message Helios…"><button class="button primary" id="send">send</button></div></div>';const send=async()=>{const field=document.querySelector('#prompt'),text=field.value.trim();if(!text)return;messages.push({role:'user',content:text});renderChat();try{messages.push({role:'assistant',content:await call('chat.send',{sessionId:currentSession,text})})}catch(e){messages.push({role:'assistant',content:'Error: '+e.message})}renderChat()};document.querySelector('#send').onclick=send;document.querySelector('#prompt').onkeydown=e=>{if(e.key==='Enter')send()}}
function renderApproval(){const box=document.querySelector('#approval'),a=approval.action||{};box.classList.remove('hidden');box.innerHTML='<div class="panel"><h1>Approval required</h1><p class="title">'+esc(a.title||'Helios requests permission')+'</p><p>'+esc(a.detail||'Review this action before continuing.')+'</p><div class="actions"><button class="button danger" id="deny">deny</button><button class="button primary" id="approve">approve</button></div></div>';const decide=async approved=>{await call('approval.respond',{approvalId:approval.approvalId,approved});approval=null;box.classList.add('hidden')};document.querySelector('#deny').onclick=()=>decide(false);document.querySelector('#approve').onclick=()=>decide(true)}
function describe(x){return x.message||x.call?.name||''}
async function reload(){snapshot=await call('snapshot');render()}
reload().catch(e=>main.innerHTML=notice('Unable to connect',e.message))
